name: 'Hello World Action'
runs:
  using: 'composite'
  steps:
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: github-actions-demo.yml
        path: .github/workflows/*
