jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
    - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
              name: github-actions-demo.yml
              path: .github/workflows/*
